In [50]:
import os
import pandas as pd
import pymongo
import certifi

from dotenv import load_dotenv
from pymongo import MongoClient

In [51]:
load_dotenv(
    os.path.abspath("../.env"),
    override=True
)

MONGODB_URL = os.getenv("MONGODB_URL")

print(
    "MONGODB_URL found:",
    bool(MONGODB_URL)
)

print(
    "Starts with:",
    MONGODB_URL[:15] if MONGODB_URL else None
)

MONGODB_URL found: True
Starts with: mongodb+srv://s

In [52]:
client = MongoClient(
    MONGODB_URL,
    tlsCAFile=certifi.where()
)

print(
    client.admin.command("ping")
)

{'ok': 1}

In [53]:
DB_NAME = "Vehicle_Insurance_Predictor"
COLLECTION_NAME = "Vehicle-Data"

database = client[DB_NAME]

collection = database[COLLECTION_NAME]

print("Database:", database.name)
print("Collection:", collection.name)

Database: Vehicle_Insurance_Predictor
Collection: Vehicle-Data

In [54]:
df = pd.read_csv("data.csv")

print("Shape:", df.shape)

df.head()

Shape: (381109, 12)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [55]:
data = df.to_dict(
    orient="records"
)

print(
    "Records to upload:",
    len(data)
)

Records to upload: 381109

In [57]:
print("Documents in Vehicle-Data:", collection.count_documents({}))

Documents in Vehicle-Data: 1443327

In [59]:
database = client["Vehicle_Insurance_Predictor"]

print("Before:", database["Vehicle-Data"].count_documents({}))

database["Vehicle-Data"].drop()

print("Vehicle-Data collection deleted.")

Before: 1443327
Vehicle-Data collection deleted.

In [60]:
print("After:", database["Vehicle-Data"].count_documents({}))

After: 0

In [61]:
collection = database["Vehicle-Data"]

print("Database:", database.name)
print("Collection:", collection.name)

Database: Vehicle_Insurance_Predictor
Collection: Vehicle-Data

In [62]:
import pandas as pd

df = pd.read_csv("data.csv")

print("Shape:", df.shape)
df.head()

Shape: (381109, 12)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [63]:
data = df.to_dict(orient="records")

print("Records to upload:", len(data))

Records to upload: 381109

In [64]:
print(database["Vehicle-Data"].count_documents({}))

0

In [65]:
batch_size = 5000

total_inserted = 0

for i in range(0, len(data), batch_size):
    batch = data[i:i + batch_size]
    
    result = collection.insert_many(batch)
    total_inserted += len(result.inserted_ids)
    
    print(f"Inserted {total_inserted} / {len(data)}")

Inserted 5000 / 381109
Inserted 10000 / 381109
Inserted 15000 / 381109
Inserted 20000 / 381109
Inserted 25000 / 381109
Inserted 30000 / 381109
Inserted 35000 / 381109
Inserted 40000 / 381109
Inserted 45000 / 381109
Inserted 50000 / 381109
Inserted 55000 / 381109
Inserted 60000 / 381109
Inserted 65000 / 381109
Inserted 70000 / 381109
Inserted 75000 / 381109
Inserted 80000 / 381109
Inserted 85000 / 381109
Inserted 90000 / 381109
Inserted 95000 / 381109
Inserted 100000 / 381109
Inserted 105000 / 381109
Inserted 110000 / 381109
Inserted 115000 / 381109
Inserted 120000 / 381109
Inserted 125000 / 381109
Inserted 130000 / 381109
Inserted 135000 / 381109
Inserted 140000 / 381109
Inserted 145000 / 381109
Inserted 150000 / 381109
Inserted 155000 / 381109
Inserted 160000 / 381109
Inserted 165000 / 381109
Inserted 170000 / 381109
Inserted 175000 / 381109
Inserted 180000 / 381109
Inserted 185000 / 381109
Inserted 190000 / 381109
Inserted 195000 / 381109
Inserted 200000 / 381109
Inserted 205000 / 381109
Inserted 210000 / 381109
Inserted 215000 / 381109
Inserted 220000 / 381109
Inserted 225000 / 381109
Inserted 230000 / 381109
Inserted 235000 / 381109
Inserted 240000 / 381109
Inserted 245000 / 381109
Inserted 250000 / 381109
Inserted 255000 / 381109
Inserted 260000 / 381109
Inserted 265000 / 381109
Inserted 270000 / 381109
Inserted 275000 / 381109
Inserted 280000 / 381109
Inserted 285000 / 381109
Inserted 290000 / 381109
Inserted 295000 / 381109
Inserted 300000 / 381109
Inserted 305000 / 381109
Inserted 310000 / 381109
Inserted 315000 / 381109
Inserted 320000 / 381109
Inserted 325000 / 381109
Inserted 330000 / 381109
Inserted 335000 / 381109
Inserted 340000 / 381109
Inserted 345000 / 381109
Inserted 350000 / 381109
Inserted 355000 / 381109
Inserted 360000 / 381109
Inserted 365000 / 381109
Inserted 370000 / 381109
Inserted 375000 / 381109
Inserted 380000 / 381109
Inserted 381109 / 381109

In [ ]:
count = collection.count_documents({})

print("Documents in Vehicle-Data:", count)

Documents in Vehicle-Data: 381109